### ISSUE TITLE
使用sydney-on-wechat项目报错

### ISSUE THREAD

**Issue by Bromaomao** [JayGarland/Autoreply_Sydneybot_Reddit#2]
Worker return exception: unsupported operand type(s) for |: 'type' and 'NoneType'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrator\Desktop\bing\channel\chat_channel.py", line 154, in _handle
    reply = self._generate_reply(context)
  File "C:\Users\Administrator\Desktop\bing\channel\chat_channel.py", line 164, in _generate_reply
    e_context = PluginManager().emit_event(
  File "C:\Users\Administrator\Desktop\bing\plugins\plugin_manager.py", line 189, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\bing\plugins\role\role.py", line 104, in on_handle_context
    bot = Bridge().get_bot("chat")
  File "C:\Users\Administrator\Desktop\bing\bridge\bridge.py", line 42, in get_bot
    self.bots[typename] = create_bot(self.btype[typename])
  File "C:\Users\Administrator\Desktop\bing\bot\bot_factory.py", line 24, in create_bot
    from bot.Bing.Sydneyreply import SydneyBot
  File "C:\Users\Administrator\Desktop\bing\bot\Bing\Sydneyreply.py", line 12, in <module>
    from bot.Bing import Sydney_proess
  File "C:\Users\Administrator\Desktop\bing\bot\Bing\Sydney_proess.py", line 3, in <module>
    from bot.Bing import sydney
  File "C:\Users\Administrator\Desktop\bing\bot\Bing\sydney.py", line 214, in <module>
    proxy: str | None = _PROXY,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by JayGarland** [comment]
你可能没有创建config.json文件
1 是否使用代理-> 是-> 检查config.json文件是否存在且填入proxy address。
2 是否使用代理-> 否-> 已更新。

**Comment by Bromaomao** [comment]
> 你可能没有创建config.json文件 1 是否使用代理-> 是-> 检查config.json文件是否存在且填入proxy address。 2 是否使用代理-> 否-> 已更新。

感谢回复，我创建了config.json文件并设置了代理，刚刚更新了最新代码，还是一样报错
![f4fd9665cd1da4c7959e0d9a6461a90](https://github.com/JayGarland/Autoreply_Sydneybot_Reddit/assets/115863734/4ad05f44-29dd-480a-b5aa-dde354c42528)
![1f30b493571844a0491688370a9f9b7](https://github.com/JayGarland/Autoreply_Sydneybot_Reddit/assets/115863734/49611d37-3fe7-4aa1-bc68-3201dbc9d7ef)

**Comment by JayGarland** [comment]
你试试这个项目你能不能使用，https://github.com/juzeon/SydneyQt

**Comment by JayGarland** [comment]
![image](https://github.com/JayGarland/Autoreply_Sydneybot_Reddit/assets/128459480/f8ff950a-daee-43d0-8ded-228db056b08c)
检查控制台是否存在这个信息，不然就还是config.json不对

**Comment by Bromaomao** [comment]
> config应该没问题，请问你的python版本是多少呢
![f53bb8ebbcb02209d2f4fa26a35920b](https://github.com/JayGarland/Autoreply_Sydneybot_Reddit/assets/115863734/1c0739cc-7437-48b6-8d5c-7a25cbbb12e2)

**Comment by JayGarland** [comment]
python升级到最新版试试(>=3.11.0)

**Comment by Bromaomao** [comment]
> python升级到最新版试试(>=3.11.0)

版本升级后可以使用了，不过控制台会一直刷消息
